config/routes.rb
Rails.application.routes.draw do
  resources :campaigns do
    resources :photos
  end
  resources :charges
  devise_for :users
  resources :users, only: [:index, :show]
  root 'static#homepage'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  mount_uploader :profile_picture, ProfilePictureUploader
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_and_belongs_to_many :contributors, class_name: "User", join_table: "campaigns_users"
  mount_uploader :campaign_logo, CampaignLogoUploader
  has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :campaign_pic, CampaignPicsUploader
  belongs_to :campaign
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :campaigns
  has_many :photos
  has_and_belongs_to_many :campaigns_contributing, class_name: "Campaign", join_table: "campaigns_users"

  validates_presence_of :role

  ROLES = ["donor", "charity"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    helper_method :is_charity?

    helper_method :is_donor?

    protected

      def is_charity?
        !current_user.nil? && current_user.role == 'charity'
      end

      def is_donor?
        !current_user.role == 'donor'
      end

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :first_name, :last_name, :description, :location, :facebook_profile, :twitter_profile, :profile_picture, :role])     
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :first_name, :last_name, :description, :location, :facebook_profile, :twitter_profile, :profile_picture])
      end

      def after_sign_in_path_for(resource)
        users_path
      end
  end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :check_is_charity, except: [:index, :show]

  def index
    @campaigns = Campaign.all
  end

  def show
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_is_charity
      p current_user.role
      if current_user.role != 'charity'
        flash[:danger] = "You need to be a charity to create a campaign"
        redirect_to campaigns_path
      end
    end

    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:title, :description, :campaign_logo)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_campaign

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    @photo.campaign = @campaign

    respond_to do |format|
      if @photo.save
        format.html { redirect_to campaign_photo_path(@campaign, @photo), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to campaign_photo_path(@campaign, @photo), notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end

    def photo_params
      params.require(:photo).permit(:title, :location, :description, :campaign_pic)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    render layout: "homepage"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :campaign_logo %><br />
    <%= f.file_field :campaign_logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div class="devise_forms">
  <h3>Modify you Campaign</h3>

  <div id="edit-page">
    <%= render 'form', campaign: @campaign %>
    <%= link_to 'Show', @campaign %> |
    <%= link_to 'Back', campaigns_path %>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="campaign_top">
  <div class="campaign_title">
  <h1>Campaigns</h1>
  </div>
  <div class="campaign_button">
  <%= link_to 'Add a New Campaign', new_campaign_path, class: "btn btn-outline-primary" if is_charity? %>
  </div>
</div>
  <div class="card-columns">
    <% @campaigns.each do |campaign| %>
      <% if campaign.user_id == current_user.id || current_user.role == "donor" %>
        <div class="card">
          <%= link_to image_tag(campaign.campaign_logo.thumb, class: "card-img-top img-fluid", alt: campaign.title), campaign %>
          <div class="card-block">
            <h4 class="card-title"><%= campaign.title %></h4>
            <p class="card-text"><%= campaign.description %></p>
            <p class="card-text"><%= campaign.creator.name if is_charity? %></p>
            <small class="text-muted">Added on <%= distance_of_time_in_words(Time.now, campaign.created_at) %> ago</small></p>
            <%= link_to 'Edit', edit_campaign_path(campaign), class: "btn btn-outline-primary" if is_charity?%>
            <%= link_to 'Delete', campaign, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" if is_charity? %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/campaigns/new.html.erb
<div class="devise_forms">
  <h3>New Campaign</h3>

  <%= render 'form', campaign: @campaign %><br />
  <%= link_to 'Back', campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to image_tag(@campaign.campaign_logo.thumb.url, class: "img-rounded"), @campaign.campaign_logo.url%>
  </div>
  <div class="col-md-8">
    <p>
      <strong>Title:</strong>
      <%= @campaign.title %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @campaign.description %>
    </p>
    <p>
      <%= link_to 'Edit', edit_campaign_path(@campaign), class: "btn btn-secondary" if is_charity? %>
      <%= link_to 'Add New Photo', new_campaign_photo_path(@campaign), class: "btn btn-secondary" %>
    </p>
  </div>
</div>

<br>

<div class="card-columns">
  <% @campaign.photos.each do |photo| %>
    <div class="card">
      <%= link_to image_tag(photo.campaign_pic.thumb.url, class: "card-img-top, img-fluid", alt: photo.title), campaign_photo_path(@campaign, photo) %>
      <div class="card-block">
        <h4 class="card-title"><%= photo.title %></h4>
        <p class="card-text"><%= photo.description %></p>
        <small class="text-muted">Added on <%= distance_of_time_in_words(Time.now, photo.created_at) %> ago</small></p>
        <%= link_to 'Buy', campaign_photo_path(@campaign, photo), class: "btn btn-outline-primary" if !is_charity? %> 
        <%= link_to 'Edit', edit_campaign_photo_path(@campaign, photo), class: "btn btn-outline-primary" if is_charity? || user_session == current_user.id %>
        <%= link_to 'Delete', campaign_photo_path(@campaign, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" if is_charity? || user_session == current_user.id %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Back', campaigns_path %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <article>
      <%=label_tag(:amount, 'Donation Amount:') %>
      <%=text_field_tag(:amount) %>
    </article>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Make a Donation"
          data-amount="500"
          data-currency="gbp"
          data-bitcoin="true"
          data-locale="auto">
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAid</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light bg-faded" id="topnavbar">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <img src="/images/logo.png" alt="logo" class="navbar-brand" id="logo"></a>
              <a class="navbar-brand">Hi <%= current_user.first_name || (current_user.name if is_charity?) %>!</a>
              <li class="nav-item"><%= link_to "Campaigns", campaigns_path, class:"nav-link"%></li>
              <% if is_donor? %>
                <li class="nav-item"><%= link_to "Charities", campaigns_path, class:"nav-link btn btn-outline-secondary"%></li>
              <% end %>
              <li class="nav-item"><%= link_to "Your Profile", users_path, class:"nav-link" %></li>
              <li class="form-inline pull-xs-right"><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %></li>
          <% else %>
            <img src="/images/logo.png" alt="logo" class="navbar-brand" id="logo"></a>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "Register", new_user_registration_path, class:"nav-link" %></li>
          </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAid</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light bg-faded" id="topnavbar">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <img src="/images/logo.png" alt="logo" class="navbar-brand" id="logo"></a>
              <a class="navbar-brand">Hi <%= current_user.first_name || (current_user.name if is_charity?) %>!</a>
              <li class="nav-item"><%= link_to "Campaigns", campaigns_path, class:"nav-link"%></li>
              <% if is_donor? %>
                <li class="nav-item"><%= link_to "Charities", campaigns_path, class:"nav-link btn btn-outline-secondary"%></li>
              <% end %>
              <li class="nav-item"><%= link_to "Your Profile", users_path, class:"nav-link" %></li>
              <li class="form-inline pull-xs-right"><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %></li>
          <% else %>
            <img src="/images/logo.png" alt="logo" class="navbar-brand" id="logo"></a>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "Register", new_user_registration_path, class:"nav-link" %></li>
          </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <main class="container-flat">
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for([campaign, photo]) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
     <%= f.label :campaign_pic %><br />
     <%= f.file_field :campaign_pic %>
   </div>

  <div class="actions">
    <%= f.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="devise_forms">
  <h3>Editing Photo</h3>

  <%= render 'form', campaign: @campaign, photo: @photo %>

  <%= link_to 'Show', campaign_photo_path %> |
  <%= link_to 'Back', campaign_photos_path %>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Photos</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td><%= link_to image_tag(photo.campaign_pic.url), campaign_photo_path(@campaign, photo) %></td>
        <td><%= photo.location %></td>
        <td><%= photo.description %></td>
        <td></td>
        <td><%= link_to 'Edit', edit_campaign_photo_path(@campaign, photo) %></td>
        <td><%= link_to 'Destroy', campaign_photo_path(@campaign, photo), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_campaign_photo_path(@campaign) %>

app/views/photos/new.html.erb
<div class="devise_forms">
  <h3>New Photo</h3>

  <%= render 'form', campaign: @campaign, photo: @photo %>

  <%= link_to 'Back', campaign_photos_path %>
</div>

app/views/photos/show.html.erb
<div id="photopage">
  
  <h4>Title:</h4>
  <p><%= @photo.title %></p>


  <h4>Location:</h4>
  <p><%= @photo.location %></p>


  <h4>Description:</h4>
  <p><%= @photo.description %></p>

  <div class="image">
    <%= image_tag @photo.campaign_pic.url %>
  </div>

  <br>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Make a Donation"
          data-amount="500"
          data-currency="gbp"
          data-bitcoin="true"
          data-locale="auto"></script>
  <% if @photo.user_id == current_user.id %>
  <%= link_to 'Edit', edit_campaign_photo_path(@photo) %>
  <% end %>
   |
  <%= link_to 'Back', @campaign %>
</div>

app/views/users/index.html.erb
  <div class="row">
  <div class="col-md-4">
    <%= link_to image_tag(current_user.profile_picture.thumb.url, class: "img-rounded"), current_user.profile_picture.url %>
  </div>
  <div class="col-md-8">
    <p><%= current_user.description %></p>
    <%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-secondary" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
  </div>
</div>

<br>

<div class="card-columns">
  <% if is_charity? %>
    <% current_user.campaigns.each do |campaign| %>
      <div class="card">
        <%= link_to image_tag(campaign.campaign_logo.thumb, class: "card-img-top img-fluid"), campaign_path(campaign) %>
        <div class="card-block">
          <h4 class="card-title"><%= campaign.title %></h4>
          <p class="card-text"><%= campaign.description %></p>
          <small class="text-muted">Added on <%= distance_of_time_in_words(Time.now, campaign.created_at) %> ago</small></p>
          <%= link_to 'Edit', edit_campaign_path(campaign), class: "btn btn-outline-primary" if is_charity?%>
          <%= link_to 'Delete', campaign, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" if is_charity? %>
        </div>
      </div>
    <% end %>
  <% else %>
    <% current_user.photos.each do |photo| %>
    <div class="card">
    <%= link_to image_tag(photo.campaign_pic.url, class: "img-fluid"), campaign_photo_path(photo.campaign, photo) %>
      <div class="card-block">
        <h4 class="card-title"><%= photo.title %></h4>
        <p class="card-text"><%= photo.description %></p>
        <small class="text-muted">Added on <%= distance_of_time_in_words(Time.now, photo.campaign.created_at) %> ago</small></p>
        <%= link_to 'Edit', edit_campaign_photo_path(photo.campaign, photo), class: "btn btn-outline-primary" %>
        <%= link_to 'Delete', campaign_photo_path(photo.campaign, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
      </div>
    </div>      
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>